
  CREATE TABLE "KLAJOS"."DW_MASTER_TABLE" 
   (	"FORR_AZ" VARCHAR2(50 BYTE), 
	"SEMA" VARCHAR2(50 BYTE), 
	"TABLA_NEV" VARCHAR2(200 BYTE), 
	"OSZLOP_NEV" VARCHAR2(200 BYTE), 
	"OSZLOP_TIPUS" VARCHAR2(50 BYTE), 
	"OSZLOP_HOSSZ" VARCHAR2(50 BYTE), 
	"FK_TABLA" VARCHAR2(200 BYTE), 
	"FK_TABLA_OSZLOP" VARCHAR2(200 BYTE), 
	"PK" VARCHAR2(10 BYTE), 
	"OSZLOP_HOSZ_FORAS" NUMBER(5,0), 
	"ST_TABLA_NEV" VARCHAR2(200 BYTE), 
	"ST_OSZLOP_NEV" VARCHAR2(200 BYTE), 
	"ST_OSZLOP_TIPUS" VARCHAR2(50 BYTE), 
	"ST_OSZLOP_HOSSZ" VARCHAR2(50 BYTE), 
	"ST_FK_TABLA" VARCHAR2(200 BYTE), 
	"ST_FK_TABLA_OSZLOP" VARCHAR2(200 BYTE), 
	"ST_PK" VARCHAR2(10 BYTE), 
	"ST_SERVICE_TYPE1" VARCHAR2(200 BYTE), 
	"ST_SERVICE_TYPE2" VARCHAR2(200 BYTE)
   )  ;
---------------------

  CREATE TABLE "KLAJOS"."DW_SERVICE_LOG" 
   (	"TYPE1" NUMBER(10,0), 
	"TYPE2" NUMBER(10,0), 
	"TABLA_OSZLOP" VARCHAR2(200 BYTE), 
	"SZOVEG" VARCHAR2(2000 BYTE)
   ) ;
  ----------------
    CREATE TABLE "KLAJOS"."DW_SERVICE_TABLE" 
   (	"TYPE0" VARCHAR2(200 BYTE), 
	"TYPE1" VARCHAR2(200 BYTE), 
	"TYPE2" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"FIELD_TYPE" VARCHAR2(200 BYTE), 
	"FIELD_LENG" VARCHAR2(200 BYTE), 
	"FIELD_KEY" VARCHAR2(200 BYTE), 
	"CONSTRAIT" VARCHAR2(200 BYTE)
   )  ;
  ---------------
  
  CREATE TABLE "KLAJOS"."DW_DB_TYPE_CONV_TABLA" 
   (	"DB_TYPE" VARCHAR2(200 BYTE), 
	"VERSIO" VARCHAR2(200 BYTE), 
	"DEFAULT_VALUE" VARCHAR2(200 BYTE), 
	"FIELD_TYPE" VARCHAR2(200 BYTE), 
	"FIELD_LENGHT" VARCHAR2(200 BYTE), 
	"ID" VARCHAR2(200 BYTE), 
	"TYPE1" VARCHAR2(200 BYTE), 
	"TYPE2" VARCHAR2(200 BYTE)
   ) ;